name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      run: echo ${{ secrets.Za6N?KCVnv2-2fw }} | docker login -u ${{ secrets.mgv1n23@soton.ac.uk }} --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t myapp:latest .
        docker tag myapp:latest mansaavats/myapp:latest
        docker push mansaavats/myapp:latest

    - name: Deploy to Kubernetes
  uses: actions/kubernetes-action@v1.1.0
  with:
    kubeconfig: ${{ secrets. 
      apiVersion:v1
      clusters:
      - cluster:
          certificate-authority-data: DATA+OMITTED
          server: https://kubernetes.docker.internal:6443
        name: docker-desktop
      contexts:
      - context:
          cluster: docker-desktop
          user: docker-desktop
        name: docker-desktop
      current-context: docker-desktop
      kind: Config
      preferences: {}
      users:
      - name: docker-desktop
        user:
          client-certificate-data: DATA+OMITTED
          client-key-data: DATA+OMITTED}}
    manifests: |
      ./deployment.yaml
